name: main
on:
    push:
        branches:
            - master
jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Dependencies
              run: |
                sudo apt-get update -y
                sudo apt-get install cmake build-essential mesa-common-dev -y
            - name: Compiles to Linux
              run: |
                cmake .
                cmake --build .
            - name: Uploads Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Output
                path: Output
    macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Compiles to MacOS
              run: |
                cmake .
                cmake --build .
            - name: Uploads Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Output
                path: Output

